import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactToast from "@/components/react-toast";
import { getServerSession } from "next-auth";
import AuthProvider  from "@/util/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ReactToast/>
      </body>
    </html>
  );
}
